Diagram as Code for Registry
NASA-PDS/registry pull request #194
Opened 2023-05-10 22:16 UTC by sjoshi-jpl

## 🗒️ Summary
This is an attempt to draw registry architecture diagram using [Python Code](https://diagrams.mingrammer.com/).

## ⚙️ Test Data and/or Report
- First attempt at Diagram as Code.
- Lucidchart has more detailed version - https://lucid.app/lucidchart/d2d7eb2a-352b-4105-81d6-5694f3d50f8a/edit?page=0_0&invitationId=inv_cb274122-3dbb-43bf-8535-c5700843ee35#

## ♻️ Related Issues

Rework Registry+API Architecture Diagram in LucidChart - https://github.com/nasa-pds/registry/issues/189

2023-05-11 15:41 UTC, alexdunnjpl approved these changes
Oh, neat!

2023-05-11 16:27 UTC, nutjob4life approved these changes
Pretty nifty

2023-05-11 18:47 UTC, tloubrieu-jpl requested changes
Hi @sjoshi-jpl ,

Can you simplify the readme, just providing the right command line to generate the diagrams and removing the images from the repository.

Thanks,

Thomas

2023-05-11 18:47 UTC, tloubrieu-jpl requested changes
Hi @sjoshi-jpl ,

Can you simplify the readme, just providing the right command line to generate the diagrams and removing the images from the repository.

Thanks,

Thomas

2023-05-12 14:15 UTC, sjoshi-jpl commented on diagrams/README.md
> +- Python 3.6.8 or higher
@tloubrieu-jpl this is just meant to be a recommendation, but I can switch it to 3.9 since I'm already editing the document.

2023-05-12 14:17 UTC, sjoshi-jpl commented on diagrams/README.md
> +## Providers
@tloubrieu-jpl sure, there are not too many steps. Mostly its writing custom code for your diagram so I can highlight the pre-requisite steps and step to execute the script.

2023-06-01 16:08 UTC, jordanpadams commented
@tloubrieu-jpl it looks like @sjoshi-jpl simplified this a bit. are we good for merge?

2023-06-05 21:48 UTC, tloubrieu-jpl requested changes
Hi @sjoshi-jpl ,

You just need to remove the images from this PR.

Thanks,

Thomas

2023-06-05 21:48 UTC, tloubrieu-jpl commented on diagrams/README.md
> +- Python 3.6.8 or higher
@sjoshi-jpl yes you can change that

2023-06-05 21:48 UTC, tloubrieu-jpl commented on diagrams/README.md
> +## Providers
Perfect you can keep both the steps (like a quickstart) and the links to the detailed documentation.

2023-06-05 21:48 UTC, tloubrieu-jpl commented on diagrams/README.md
> +## Providers
Most importantly @sjoshi-jpl you need to remove the images from the repository.

2023-06-19 16:32 UTC, jordanpadams commented
@sjoshi-jpl can you make the changes recommended by @tloubrieu-jpl and then  we can merge this?

2023-06-20 19:06 UTC, sjoshi-jpl commented
@tloubrieu-jpl  which images are you referring to? I removed the images that were part of the previous PR already. Let me know if I am missing something here?

Are you referring to the Provider images under README.md?

2023-07-10 17:27 UTC, tloubrieu-jpl approved these changes
Sorry for the late review.

2023-07-10 17:27 UTC, merged