add cross-links, little rewording and structure revision
NASA-PDS/registry pull request #37
Opened 2022-04-07 20:16 UTC by tloubrieu-jpl

## 🗒️ Summary
- add cross link on the prerequisite
- little rewording
- reorganized heading for update status
- add a harvest job configuration section

2022-04-07 21:08 UTC, nutjob4life approved these changes
![Looks good](https://user-images.githubusercontent.com/814813/162309227-69c9b9c0-aafe-4b95-aaac-105482d0e036.gif)

2022-04-08 01:34 UTC, tdddblog approved these changes

2022-04-08 01:41 UTC, tdddblog commented
I approved it, but we have to discuss what is the best way to handle cross references in Sphinx.

2022-04-11 16:25 UTC, jordanpadams requested changes

2022-04-11 16:25 UTC, jordanpadams commented on docs/source/admin/create_reg.rst
> + * Registry Manager command-line tool is `installed <../install/tools.html#registry-manager>`_.
@tdddblog agreed that is the "ideal" syntax but we use these inline links all over the place.

@tloubrieu-jpl take note above for the future

2022-04-11 16:25 UTC, jordanpadams commented on docs/source/user/delete_data.rst
> +**Warning:** only use if you know what you are doing
@tloubrieu-jpl +1 here. can we make this quick change?

2022-04-11 16:30 UTC, jordanpadams commented on docs/source/user/delete_data.rst
> +.. warning::
@tloubrieu-jpl @tdddblog updated

2022-04-11 16:30 UTC, jordanpadams approved these changes

2022-04-11 17:10 UTC, tloubrieu-jpl commented
@tdddblog @jordanpadams thanks for the feedback and correcting this warning. I was lazy for the cross-reference links...

2022-04-11 17:10 UTC, merged